const productData = [
    {
        // _id:1,
        name: 'T-Shirt',
        price:'70',
        slug:'Shirt',
        img: '/image/one.jpg',
        desciption: 'Some quick example text to build on the card title and make up the bulk of the card',
        rating:'4.5',
        nameOfRating: '80',
        stock: '10',
        Brand:'Easy',
        catagory:'shirt',
        coupon: 'shadin',
        discount: 20,
        discountLimit: 50,
        totalSale: 10
    },
    {
        // _id:2,
        name: 'Blazer',
        price:'200',
        slug:'Blazer',
        img: '/image/two.jpg',
        desciption: 'Some quick example text to build on the card title and make up the bulk of the card',
        rating:'5',
        nameOfRating: '109',
        stock: '5',
        Brand:'Yellow',
        catagory:'blazer',
        coupon: '',
        discount: 10,
        discountLimit: 100,
        totalSale: 100
    },
    {
        // _id:3,
        name: 'Red Shirt',
        price:'120',
        slug:'pant',
        img: '/image/three.jpg',
        desciption: 'Some quick example text to build on the card title and make up the bulk of the card',
        rating:'3',
        nameOfRating: '90',
        stock: '56',
        Brand:'Arrong',
        catagory:'shirt',
        coupon: 'Anik',
        discount: 10,
        discountLimit: 100,
        totalSale: 100
    },
    {
        // _id:4,
        name: 'Black Shirt',
        price:'120',
        slug:'short-pant',
        img: '/image/one.jpg',
        desciption: 'Some quick example text to build on the card title and make up the bulk of the card',
        rating:'4',
        nameOfRating: '100',
        stock: '32',
        Brand:'Tex Point',
        catagory:'tshirt',
        coupon: 'FENI02M',
        discount: 10,
        discountLimit: 100,
        totalSale: 90
    },
    {
        // _id:5,
        name: 'T-shirt2',
        price:'70',
        slug:'Shirt2',
        img: '/image/one.jpg',
        desciption: 'Some quick example text to build on the card title and make up the bulk of the card',
        rating:'4.5',
        nameOfRating: '80',
        stock: '10',
        Brand:'Easy',
        catagory:'tshirt',
        coupon: 'AMARI12M',
        discount: 20,
        discountLimit: 100,
        totalSale: 49
    },
    {
        // _id:6,
        name: 'Blazer2',
        price:'200',
        slug:'Blazer2',
        img: '/image/two.jpg',
        desciption: 'Some quick example text to build on the card title and make up the bulk of the card',
        rating:'5',
        nameOfRating: '109',
        stock: '5',
        Brand:'Yellow',
        catagory:'blazer',
        coupon: 'DINKAL20NF',
        discount: 40,
        discountLimit: 40,
        totalSale: 42
    },
    {
        // _id:7,
        name: 'Red2 Shirt',
        price:'120',
        slug:'pant2',
        img: '/image/three.jpg',
        desciption: 'Some quick example text to build on the card title and make up the bulk of the card',
        rating:'3',
        nameOfRating: '90',
        stock: '56',
        Brand:'Arrong',
        catagory:'Exclusive shirt',
        coupon: 'SHADIN26MC',
        discount: 10,
        discountLimit: 100,
        totalSale: 60
    },
    {
        // _id:8,
        name: 'Black2 Shirt',
        price:'120',
        slug:'short-pant2',
        img: '/image/one.jpg',
        desciption: 'Some quick example text to build on the card title and make up the bulk of the card',
        rating:'4',
        nameOfRating: '100',
        stock: '32',
        Brand:'Tex Point',
        catagory:'Exclusive shirt',
        coupon: 'BIKE100BR',
        discount: 30,
        discountLimit: 80,
        totalSale: 50
    },
]

export default productData